// @ts-nocheck
export const products = [
    {
        id: 1,
        name: "Apple",
        category: "fruit",
        calories: 52,
        vitamins: ["A", "C", "K"],
        color: "red",
    },
    {
        id: 2,
        name: "Banana",
        category: "fruit",
        calories: 89,
        vitamins: ["B6", "C"],
        color: "yellow",
    },
    {
        id: 3,
        name: "Grapes",
        category: "fruit",
        calories: 67,
        vitamins: ["C", "K"],
        color: "purple",
    },
    {
        id: 4,
        name: "Pear",
        category: "fruit",
        calories: 57,
        vitamins: ["C", "K"],
        color: "green",
    },
    {
        id: 5,
        name: "Peach",
        category: "fruit",
        calories: 39,
        vitamins: ["A", "C"],
        color: "orange",
    },
    {
        id: 6,
        name: "Plum",
        category: "fruit",
        calories: 46,
        vitamins: ["C", "K"],
        color: "purple",
    },
    {
        id: 7,
        name: "Apricot",
        category: "fruit",
        calories: 48,
        vitamins: ["A", "C"],
        color: "orange",
    },
    {
        id: 8,
        name: "Cherry",
        category: "fruit",
        calories: 63,
        vitamins: ["A", "C"],
        color: "red",
    },
    {
        id: 9,
        name: "Strawberry",
        category: "fruit",
        calories: 33,
        vitamins: ["C", "A"],
        color: "red",
    },
    {
        id: 10,
        name: "Blueberry",
        category: "fruit",
        calories: 57,
        vitamins: ["C", "K"],
        color: "blue",
    },
    {
        id: 11,
        name: "Raspberry",
        category: "fruit",
        calories: 52,
        vitamins: ["C", "K"],
        color: "red",
    },
    {
        id: 12,
        name: "Blackberry",
        category: "fruit",
        calories: 43,
        vitamins: ["C", "K"],
        color: "black",
    },
    {
        id: 13,
        name: "Pineapple",
        category: "fruit",
        calories: 50,
        vitamins: ["C", "B1"],
        color: "yellow",
    },
    {
        id: 14,
        name: "Mango",
        category: "fruit",
        calories: 60,
        vitamins: ["A", "C"],
        color: "orange",
    },
    {
        id: 15,
        name: "Papaya",
        category: "fruit",
        calories: 43,
        vitamins: ["C", "A"],
        color: "orange",
    },
    {
        id: 16,
        name: "Watermelon",
        category: "fruit",
        calories: 30,
        vitamins: ["A", "C"],
        color: "green",
    },
    {
        id: 17,
        name: "Melon",
        category: "fruit",
        calories: 34,
        vitamins: ["C"],
        color: "green",
    },
    {
        id: 18,
        name: "Kiwi",
        category: "fruit",
        calories: 61,
        vitamins: ["C", "K"],
        color: "brown",
    },
    {
        id: 19,
        name: "Avocado",
        category: "fruit",
        calories: 160,
        vitamins: ["E", "K"],
        color: "green",
    },
    {
        id: 20,
        name: "Pomegranate",
        category: "fruit",
        calories: 83,
        vitamins: ["C", "K"],
        color: "red",
    },
    {
        id: 21,
        name: "Fig",
        category: "fruit",
        calories: 74,
        vitamins: ["K", "B6"],
        color: "purple",
    },
    {
        id: 22,
        name: "Date",
        category: "fruit",
        calories: 282,
        vitamins: ["B6", "K"],
        color: "brown",
    },
    {
        id: 23,
        name: "Coconut",
        category: "fruit",
        calories: 354,
        vitamins: ["C", "E"],
        color: "brown",
    },
    {
        id: 24,
        name: "Lychee",
        category: "fruit",
        calories: 66,
        vitamins: ["C", "B6"],
        color: "red",
    },
    {
        id: 25,
        name: "Passion Fruit",
        category: "fruit",
        calories: 97,
        vitamins: ["A", "C"],
        color: "purple",
    },
    {
        id: 26,
        name: "Guava",
        category: "fruit",
        calories: 68,
        vitamins: ["C", "A"],
        color: "green",
    },
    {
        id: 27,
        name: "Dragon Fruit",
        category: "fruit",
        calories: 50,
        vitamins: ["C", "B1"],
        color: "pink",
    },
    {
        id: 28,
        name: "Jackfruit",
        category: "fruit",
        calories: 95,
        vitamins: ["C", "B6"],
        color: "green",
    },
    {
        id: 29,
        name: "Starfruit",
        category: "fruit",
        calories: 31,
        vitamins: ["C", "B5"],
        color: "yellow",
    },
    {
        id: 30,
        name: "Cantaloupe",
        category: "fruit",
        calories: 34,
        vitamins: ["A", "C"],
        color: "orange",
    },
    {
        id: 31,
        name: "Nectarine",
        category: "fruit",
        calories: 44,
        vitamins: ["A", "C"],
        color: "orange",
    },
    {
        id: 32,
        name: "Red Currant",
        category: "fruit",
        calories: 56,
        vitamins: ["C", "K"],
        color: "red",
    },
    {
        id: 33,
        name: "Black Currant",
        category: "fruit",
        calories: 63,
        vitamins: ["C", "K"],
        color: "black",
    },
    {
        id: 34,
        name: "Mulberry",
        category: "fruit",
        calories: 43,
        vitamins: ["C", "K"],
        color: "purple",
    },
    {
        id: 35,
        name: "Gooseberry",
        category: "fruit",
        calories: 44,
        vitamins: ["C", "A"],
        color: "green",
    },
    {
        id: 36,
        name: "Persimmon",
        category: "fruit",
        calories: 81,
        vitamins: ["A", "C"],
        color: "orange",
    },
    {
        id: 37,
        name: "Quince",
        category: "fruit",
        calories: 57,
        vitamins: ["C"],
        color: "yellow",
    },
    {
        id: 38,
        name: "Longan",
        category: "fruit",
        calories: 60,
        vitamins: ["C", "B2"],
        color: "brown",
    },
    {
        id: 39,
        name: "Elderberry",
        category: "fruit",
        calories: 73,
        vitamins: ["C", "A"],
        color: "black",
    },
    {
        id: 40,
        name: "Cranberry",
        category: "fruit",
        calories: 46,
        vitamins: ["C", "E"],
        color: "red",
    },
    {
        id: 41,
        name: "Prune",
        category: "fruit",
        calories: 240,
        vitamins: ["A", "K"],
        color: "dark purple",
    },
    {
        id: 42,
        name: "Blood Orange",
        category: "fruit",
        calories: 47,
        vitamins: ["C", "A"],
        color: "red",
    },
    {
        id: 43,
        name: "Ugli Fruit",
        category: "fruit",
        calories: 45,
        vitamins: ["C"],
        color: "green",
    },
    {
        id: 44,
        name: "Rambutan",
        category: "fruit",
        calories: 82,
        vitamins: ["C", "B3"],
        color: "red",
    },
    {
        id: 45,
        name: "Cherimoya",
        category: "fruit",
        calories: 75,
        vitamins: ["C", "B6"],
        color: "green",
    },
    {
        id: 46,
        name: "Soursop",
        category: "fruit",
        calories: 66,
        vitamins: ["C", "B1"],
        color: "green",
    },
    {
        id: 47,
        name: "Mamey Sapote",
        category: "fruit",
        calories: 120,
        vitamins: ["A", "C"],
        color: "orange",
    },
    {
        id: 48,
        name: "Ackee",
        category: "fruit",
        calories: 151,
        vitamins: ["B1", "C"],
        color: "red",
    },
    {
        id: 49,
        name: "Feijoa",
        category: "fruit",
        calories: 55,
        vitamins: ["C", "A"],
        color: "green",
    },
    {
        id: 50,
        name: "Jabuticaba",
        category: "fruit",
        calories: 58,
        vitamins: ["C", "K"],
        color: "purple",
    },
    {
        id: 51,
        name: "Salak (Snake Fruit)",
        category: "fruit",
        calories: 82,
        vitamins: ["C", "B2"],
        color: "brown",
    },
    {
        id: 52,
        name: "Miracle Fruit",
        category: "fruit",
        calories: 2,
        vitamins: ["A", "C"],
        color: "red",
    },
    {
        id: 53,
        name: "Nashi Pear",
        category: "fruit",
        calories: 42,
        vitamins: ["C", "K"],
        color: "yellow",
    },
    {
        id: 54,
        name: "Breadfruit",
        category: "fruit",
        calories: 103,
        vitamins: ["C", "B6"],
        color: "green",
    },
    {
        id: 55,
        name: "Pawpaw",
        category: "fruit",
        calories: 80,
        vitamins: ["A", "C"],
        color: "green",
    },
    {
        id: 56,
        name: "Ugni (Chilean Guava)",
        category: "fruit",
        calories: 61,
        vitamins: ["C"],
        color: "purple",
    },
    {
        id: 57,
        name: "White Sapote",
        category: "fruit",
        calories: 83,
        vitamins: ["C", "A"],
        color: "green",
    },
    {
        id: 58,
        name: "Black Sapote",
        category: "fruit",
        calories: 68,
        vitamins: ["C", "B6"],
        color: "dark brown",
    },
    {
        id: 59,
        name: "Jujube",
        category: "fruit",
        calories: 79,
        vitamins: ["C", "B6"],
        color: "red",
    },
    {
        id: 60,
        name: "Medlar",
        category: "fruit",
        calories: 47,
        vitamins: ["C", "A"],
        color: "brown",
    },
    {
        id: 61,
        name: "Huckleberry",
        category: "fruit",
        calories: 37,
        vitamins: ["C", "K"],
        color: "blue",
    },
    {
        id: 62,
        name: "Bilberry",
        category: "fruit",
        calories: 44,
        vitamins: ["C", "K"],
        color: "blue",
    },
    {
        id: 63,
        name: "Boysenberry",
        category: "fruit",
        calories: 50,
        vitamins: ["C", "K"],
        color: "dark purple",
    },
    {
        id: 64,
        name: "Marionberry",
        category: "fruit",
        calories: 50,
        vitamins: ["C", "K"],
        color: "black",
    },
    {
        id: 65,
        name: "Tayberry",
        category: "fruit",
        calories: 43,
        vitamins: ["C", "K"],
        color: "reddish",
    },
    {
        id: 66,
        name: "Sea Buckthorn",
        category: "fruit",
        calories: 82,
        vitamins: ["C", "E"],
        color: "orange",
    },
    {
        id: 67,
        name: "Acerola",
        category: "fruit",
        calories: 32,
        vitamins: ["C", "A"],
        color: "red",
    },
    {
        id: 68,
        name: "Carambola (Starfruit)",
        category: "fruit",
        calories: 31,
        vitamins: ["C", "A"],
        color: "yellow",
    },
    {
        id: 69,
        name: "Pitaya (Dragonfruit)",
        category: "fruit",
        calories: 60,
        vitamins: ["C", "B1"],
        color: "pink",
    },
    {
        id: 70,
        name: "Durian",
        category: "fruit",
        calories: 147,
        vitamins: ["C", "B6"],
        color: "green",
    },
    {
        id: 71,
        name: "Sweetsop (Sugar Apple)",
        category: "fruit",
        calories: 94,
        vitamins: ["C", "B1"],
        color: "green",
    },
    {
        id: 72,
        name: "Prickly Pear",
        category: "fruit",
        calories: 41,
        vitamins: ["C", "B6"],
        color: "pink",
    },
    {
        id: 73,
        name: "Naranjilla",
        category: "fruit",
        calories: 44,
        vitamins: ["C", "A"],
        color: "orange",
    },
    {
        id: 74,
        name: "Loquat",
        category: "fruit",
        calories: 47,
        vitamins: ["A", "C"],
        color: "yellow",
    },
    {
        id: 75,
        name: "Apple Pear",
        category: "fruit",
        calories: 50,
        vitamins: ["C", "K"],
        color: "green",
    },
    {
        id: 76,
        name: "Plantain",
        category: "fruit",
        calories: 122,
        vitamins: ["B6", "C"],
        color: "green",
    },
    {
        id: 77,
        name: "Camu Camu",
        category: "fruit",
        calories: 17,
        vitamins: ["C"],
        color: "red",
    },
    {
        id: 78,
        name: "Guarana Fruit",
        category: "fruit",
        calories: 100,
        vitamins: ["C", "B2"],
        color: "red",
    },
    {
        id: 79,
        name: "Uva‑ursi Berry",
        category: "fruit",
        calories: 104,
        vitamins: ["C"],
        color: "red",
    },
    {
        id: 80,
        name: "Myrtle Berry",
        category: "fruit",
        calories: 44,
        vitamins: ["C", "A"],
        color: "dark",
    },
    {
        id: 81,
        name: "Kiwiberry",
        category: "fruit",
        calories: 61,
        vitamins: ["C", "K"],
        color: "green",
    },
    {
        id: 82,
        name: "Boysenapple",
        category: "fruit",
        calories: 52,
        vitamins: ["C"],
        color: "purple",
    },
    {
        id: 83,
        name: "Lingonberry",
        category: "fruit",
        calories: 50,
        vitamins: ["C", "A"],
        color: "red",
    },
    {
        id: 84,
        name: "Goji Berry",
        category: "fruit",
        calories: 349,
        vitamins: ["A", "C"],
        color: "orange",
    },
    {
        id: 85,
        name: "Black Sapote (chocolate)",
        category: "fruit",
        calories: 68,
        vitamins: ["C"],
        color: "dark brown",
    },
    {
        id: 86,
        name: "White Mulberry",
        category: "fruit",
        calories: 43,
        vitamins: ["C", "K"],
        color: "white",
    },
    {
        id: 87,
        name: "Red Mulberry",
        category: "fruit",
        calories: 43,
        vitamins: ["C", "K"],
        color: "red",
    },
    {
        id: 88,
        name: "Breadnut",
        category: "fruit",
        calories: 115,
        vitamins: ["C", "B6"],
        color: "green",
    },
    {
        id: 89,
        name: "Maypop",
        category: "fruit",
        calories: 39,
        vitamins: ["A", "C"],
        color: "yellow",
    },
    {
        id: 90,
        name: "Sapodilla",
        category: "fruit",
        calories: 83,
        vitamins: ["A", "C"],
        color: "brown",
    },

    // --- Vegetables ---
    {
        id: 91,
        name: "Carrot",
        category: "vegetable",
        calories: 41,
        vitamins: ["A", "K", "B6"],
        color: "orange",
    },
    {
        id: 92,
        name: "Potato",
        category: "vegetable",
        calories: 77,
        vitamins: ["B6", "C"],
        color: "brown",
    },
    {
        id: 93,
        name: "Sweet Potato",
        category: "vegetable",
        calories: 86,
        vitamins: ["A", "C"],
        color: "orange",
    },
    {
        id: 94,
        name: "Onion",
        category: "vegetable",
        calories: 40,
        vitamins: ["C", "B6"],
        color: "white",
    },
    {
        id: 95,
        name: "Garlic",
        category: "vegetable",
        calories: 149,
        vitamins: ["C", "B6"],
        color: "white",
    },
    {
        id: 96,
        name: "Tomato",
        category: "vegetable",
        calories: 18,
        vitamins: ["A", "C", "K"],
        color: "red",
    },
    {
        id: 97,
        name: "Cucumber",
        category: "vegetable",
        calories: 15,
        vitamins: ["C", "K"],
        color: "green",
    },
    {
        id: 98,
        name: "Bell Pepper (Red)",
        category: "vegetable",
        calories: 31,
        vitamins: ["A", "C"],
        color: "red",
    },
    {
        id: 99,
        name: "Bell Pepper (Green)",
        category: "vegetable",
        calories: 20,
        vitamins: ["A", "C"],
        color: "green",
    },
    {
        id: 100,
        name: "Broccoli",
        category: "vegetable",
        calories: 34,
        vitamins: ["C", "K"],
        color: "green",
    },
    {
        id: 101,
        name: "Cauliflower",
        category: "vegetable",
        calories: 25,
        vitamins: ["C", "K"],
        color: "white",
    },
    {
        id: 102,
        name: "Spinach",
        category: "vegetable",
        calories: 23,
        vitamins: ["A", "C", "K"],
        color: "dark green",
    },
    {
        id: 103,
        name: "Lettuce",
        category: "vegetable",
        calories: 15,
        vitamins: ["A", "C", "K"],
        color: "green",
    },
    {
        id: 104,
        name: "Cabbage",
        category: "vegetable",
        calories: 25,
        vitamins: ["C", "K"],
        color: "green",
    },
    {
        id: 105,
        name: "Zucchini",
        category: "vegetable",
        calories: 17,
        vitamins: ["C", "A"],
        color: "green",
    },
    {
        id: 106,
        name: "Eggplant",
        category: "vegetable",
        calories: 25,
        vitamins: ["B6", "K"],
        color: "purple",
    },
    {
        id: 107,
        name: "Pumpkin",
        category: "vegetable",
        calories: 26,
        vitamins: ["A", "C"],
        color: "orange",
    },
    {
        id: 108,
        name: "Beetroot",
        category: "vegetable",
        calories: 43,
        vitamins: ["A", "C"],
        color: "red",
    },
    {
        id: 109,
        name: "Radish",
        category: "vegetable",
        calories: 16,
        vitamins: ["C", "B6"],
        color: "pink",
    },
    {
        id: 110,
        name: "Peas",
        category: "vegetable",
        calories: 81,
        vitamins: ["A", "C", "K"],
        color: "green",
    },
    {
        id: 111,
        name: "Corn",
        category: "vegetable",
        calories: 86,
        vitamins: ["B1", "C"],
        color: "yellow",
    },
    {
        id: 112,
        name: "Celery",
        category: "vegetable",
        calories: 16,
        vitamins: ["A", "K"],
        color: "light green",
    },
    {
        id: 113,
        name: "Asparagus",
        category: "vegetable",
        calories: 20,
        vitamins: ["A", "C", "K"],
        color: "green",
    },
    {
        id: 114,
        name: "Mushroom",
        category: "vegetable",
        calories: 22,
        vitamins: ["B2", "D"],
        color: "beige",
    },
    {
        id: 115,
        name: "Kale",
        category: "vegetable",
        calories: 49,
        vitamins: ["A", "C", "K"],
        color: "dark green",
    },
    {
        id: 116,
        name: "Collard Greens",
        category: "vegetable",
        calories: 32,
        vitamins: ["A", "C", "K"],
        color: "green",
    },
    {
        id: 117,
        name: "Brussels Sprouts",
        category: "vegetable",
        calories: 43,
        vitamins: ["C", "K"],
        color: "green",
    },
    {
        id: 118,
        name: "Artichoke",
        category: "vegetable",
        calories: 47,
        vitamins: ["C", "K"],
        color: "green",
    },
    {
        id: 119,
        name: "Leek",
        category: "vegetable",
        calories: 61,
        vitamins: ["A", "C"],
        color: "light green",
    },
    {
        id: 120,
        name: "Fennel",
        category: "vegetable",
        calories: 31,
        vitamins: ["C", "A"],
        color: "white",
    },
    {
        id: 121,
        name: "Squash (Butternut)",
        category: "vegetable",
        calories: 45,
        vitamins: ["A", "C"],
        color: "orange",
    },
    {
        id: 122,
        name: "Turnip",
        category: "vegetable",
        calories: 28,
        vitamins: ["C", "K"],
        color: "white",
    },
    {
        id: 123,
        name: "Parsnip",
        category: "vegetable",
        calories: 75,
        vitamins: ["C", "B6"],
        color: "beige",
    },
    {
        id: 124,
        name: "Okra",
        category: "vegetable",
        calories: 33,
        vitamins: ["C", "K"],
        color: "green",
    },
    {
        id: 125,
        name: "Radicchio",
        category: "vegetable",
        calories: 23,
        vitamins: ["K", "C"],
        color: "red",
    },
    {
        id: 126,
        name: "Swiss Chard",
        category: "vegetable",
        calories: 19,
        vitamins: ["A", "C", "K"],
        color: "green",
    },
    {
        id: 127,
        name: "Bok Choy",
        category: "vegetable",
        calories: 13,
        vitamins: ["A", "C", "K"],
        color: "light green",
    },
    {
        id: 128,
        name: "Rhubarb",
        category: "vegetable",
        calories: 21,
        vitamins: ["C", "K"],
        color: "red",
    },
    {
        id: 129,
        name: "Watercress",
        category: "vegetable",
        calories: 11,
        vitamins: ["A", "C", "K"],
        color: "green",
    },
    {
        id: 130,
        name: "Arugula",
        category: "vegetable",
        calories: 25,
        vitamins: ["A", "C", "K"],
        color: "green",
    },
    {
        id: 131,
        name: "Mustard Greens",
        category: "vegetable",
        calories: 27,
        vitamins: ["A", "C", "K"],
        color: "green",
    },
    {
        id: 132,
        name: "Endive",
        category: "vegetable",
        calories: 17,
        vitamins: ["A", "C", "K"],
        color: "pale green",
    },
    {
        id: 133,
        name: "Escarole",
        category: "vegetable",
        calories: 18,
        vitamins: ["A", "C", "K"],
        color: "green",
    },
    {
        id: 134,
        name: "Chicory",
        category: "vegetable",
        calories: 23,
        vitamins: ["A", "C", "K"],
        color: "light green",
    },
    {
        id: 135,
        name: "Fiddlehead Fern",
        category: "vegetable",
        calories: 34,
        vitamins: ["A", "C", "K"],
        color: "green",
    },
    {
        id: 136,
        name: "Seaweed (Wakame)",
        category: "vegetable",
        calories: 45,
        vitamins: ["A", "C", "K"],
        color: "dark green",
    },
    {
        id: 137,
        name: "Seaweed (Nori)",
        category: "vegetable",
        calories: 35,
        vitamins: ["A", "C"],
        color: "dark purple",
    },
    {
        id: 138,
        name: "Edamame",
        category: "vegetable",
        calories: 121,
        vitamins: ["A", "C", "K"],
        color: "green",
    },
    {
        id: 139,
        name: "Bamboo Shoots",
        category: "vegetable",
        calories: 27,
        vitamins: ["B6", "C"],
        color: "light yellow",
    },
    {
        id: 140,
        name: "Water Spinach",
        category: "vegetable",
        calories: 19,
        vitamins: ["A", "C", "K"],
        color: "green",
    },
    {
        id: 141,
        name: "Mung Bean Sprouts",
        category: "vegetable",
        calories: 30,
        vitamins: ["C", "K"],
        color: "white",
    },
    {
        id: 142,
        name: "Snow Peas",
        category: "vegetable",
        calories: 42,
        vitamins: ["C", "A"],
        color: "green",
    },
    {
        id: 143,
        name: "Sugar Snap Peas",
        category: "vegetable",
        calories: 42,
        vitamins: ["C", "A"],
        color: "green",
    },
    {
        id: 144,
        name: "Broccolini",
        category: "vegetable",
        calories: 35,
        vitamins: ["C", "K", "A"],
        color: "green",
    },
    {
        id: 145,
        name: "Jerusalem Artichoke",
        category: "vegetable",
        calories: 73,
        vitamins: ["C", "B6"],
        color: "brown",
    },
    {
        id: 146,
        name: "Taro",
        category: "vegetable",
        calories: 142,
        vitamins: ["C", "B6"],
        color: "light brown",
    },
    {
        id: 147,
        name: "Cassava",
        category: "vegetable",
        calories: 160,
        vitamins: ["C", "B6"],
        color: "white",
    },
    {
        id: 148,
        name: "Jicama",
        category: "vegetable",
        calories: 38,
        vitamins: ["C", "B6"],
        color: "light brown",
    },
    {
        id: 149,
        name: "Yam",
        category: "vegetable",
        calories: 118,
        vitamins: ["C", "B6"],
        color: "purple",
    },
    {
        id: 150,
        name: "Black‑eyed Peas",
        category: "vegetable",
        calories: 339,
        vitamins: ["A", "C", "K"],
        color: "beige",
    },

    // --- Citrus ---
    {
        id: 151,
        name: "Orange",
        category: "citrus",
        calories: 47,
        vitamins: ["C", "B1", "B9"],
        color: "orange",
    },
    {
        id: 152,
        name: "Lemon",
        category: "citrus",
        calories: 29,
        vitamins: ["C", "B6"],
        color: "yellow",
    },
    {
        id: 153,
        name: "Lime",
        category: "citrus",
        calories: 30,
        vitamins: ["C"],
        color: "green",
    },
    {
        id: 154,
        name: "Grapefruit",
        category: "citrus",
        calories: 42,
        vitamins: ["C", "A"],
        color: "pink",
    },
    {
        id: 155,
        name: "Mandarin",
        category: "citrus",
        calories: 53,
        vitamins: ["C", "A"],
        color: "orange",
    },
    {
        id: 156,
        name: "Tangerine",
        category: "citrus",
        calories: 53,
        vitamins: ["C", "A"],
        color: "orange",
    },
    {
        id: 157,
        name: "Clementine",
        category: "citrus",
        calories: 47,
        vitamins: ["C", "A"],
        color: "orange",
    },
    {
        id: 158,
        name: "Pomelo",
        category: "citrus",
        calories: 38,
        vitamins: ["C", "A"],
        color: "green",
    },
    {
        id: 159,
        name: "Bergamot",
        category: "citrus",
        calories: 36,
        vitamins: ["C"],
        color: "green",
    },
    {
        id: 160,
        name: "Kumquat",
        category: "citrus",
        calories: 71,
        vitamins: ["C"],
        color: "orange",
    },
    {
        id: 161,
        name: "Yuzu",
        category: "citrus",
        calories: 20,
        vitamins: ["C", "A"],
        color: "yellow",
    },
    {
        id: 162,
        name: "Kaffir Lime",
        category: "citrus",
        calories: 30,
        vitamins: ["C"],
        color: "green",
    },
    {
        id: 163,
        name: "Blood Orange (Citrus)",
        category: "citrus",
        calories: 50,
        vitamins: ["C", "A"],
        color: "dark red",
    },
    {
        id: 164,
        name: "Sour Orange",
        category: "citrus",
        calories: 47,
        vitamins: ["C"],
        color: "orange",
    },
    {
        id: 165,
        name: "Bitter Orange",
        category: "citrus",
        calories: 49,
        vitamins: ["C"],
        color: "orange",
    },
    {
        id: 166,
        name: "Key Lime",
        category: "citrus",
        calories: 30,
        vitamins: ["C"],
        color: "green",
    },
    {
        id: 167,
        name: "Seville Orange",
        category: "citrus",
        calories: 45,
        vitamins: ["C", "A"],
        color: "orange",
    },
    {
        id: 168,
        name: "Calamondin",
        category: "citrus",
        calories: 50,
        vitamins: ["C"],
        color: "orange",
    },
    {
        id: 169,
        name: "Citron",
        category: "citrus",
        calories: 30,
        vitamins: ["C"],
        color: "yellow",
    },
    {
        id: 170,
        name: "Mandarinquat",
        category: "citrus",
        calories: 50,
        vitamins: ["C"],
        color: "orange",
    },

    // --- More Fruits & Vegetables to reach 200 ---
    {
        id: 171,
        name: "Mangosteen",
        category: "fruit",
        calories: 73,
        vitamins: ["C", "B1"],
        color: "purple",
    },
    {
        id: 172,
        name: "Rambutan",
        category: "fruit",
        calories: 82,
        vitamins: ["C", "B3"],
        color: "red",
    },
    {
        id: 173,
        name: "Cherimoya",
        category: "fruit",
        calories: 75,
        vitamins: ["C", "B6"],
        color: "green",
    },
    {
        id: 174,
        name: "Mamey Sapote",
        category: "fruit",
        calories: 120,
        vitamins: ["A", "C"],
        color: "orange",
    },
    {
        id: 175,
        name: "Ackee",
        category: "fruit",
        calories: 151,
        vitamins: ["B1", "C"],
        color: "red",
    },
    {
        id: 176,
        name: "Feijoa",
        category: "fruit",
        calories: 55,
        vitamins: ["C", "A"],
        color: "green",
    },
    {
        id: 177,
        name: "Jabuticaba",
        category: "fruit",
        calories: 58,
        vitamins: ["C", "K"],
        color: "purple",
    },
    {
        id: 178,
        name: "Salak",
        category: "fruit",
        calories: 82,
        vitamins: ["C", "B2"],
        color: "brown",
    },
    {
        id: 179,
        name: "Miracle Fruit",
        category: "fruit",
        calories: 2,
        vitamins: ["A", "C"],
        color: "red",
    },
    {
        id: 180,
        name: "Breadfruit",
        category: "fruit",
        calories: 103,
        vitamins: ["C", "B6"],
        color: "green",
    },
    {
        id: 181,
        name: "Pawpaw",
        category: "fruit",
        calories: 80,
        vitamins: ["A", "C"],
        color: "green",
    },
    {
        id: 182,
        name: "Ugni",
        category: "fruit",
        calories: 61,
        vitamins: ["C"],
        color: "purple",
    },
    {
        id: 183,
        name: "White Sapote",
        category: "fruit",
        calories: 83,
        vitamins: ["C", "A"],
        color: "green",
    },
    {
        id: 184,
        name: "Black Sapote",
        category: "fruit",
        calories: 68,
        vitamins: ["C", "B6"],
        color: "dark brown",
    },
    {
        id: 185,
        name: "Jujube",
        category: "fruit",
        calories: 79,
        vitamins: ["C", "B6"],
        color: "red",
    },
    {
        id: 186,
        name: "Medlar",
        category: "fruit",
        calories: 47,
        vitamins: ["C", "A"],
        color: "brown",
    },
    {
        id: 187,
        name: "Huckleberry",
        category: "fruit",
        calories: 37,
        vitamins: ["C", "K"],
        color: "blue",
    },
    {
        id: 188,
        name: "Bilberry",
        category: "fruit",
        calories: 44,
        vitamins: ["C", "K"],
        color: "blue",
    },
    {
        id: 189,
        name: "Boysenberry",
        category: "fruit",
        calories: 50,
        vitamins: ["C", "K"],
        color: "purple",
    },
    {
        id: 190,
        name: "Marionberry",
        category: "fruit",
        calories: 50,
        vitamins: ["C", "K"],
        color: "black",
    },
    {
        id: 191,
        name: "Tayberry",
        category: "fruit",
        calories: 43,
        vitamins: ["C", "K"],
        color: "reddish",
    },
    {
        id: 192,
        name: "Sea Buckthorn",
        category: "fruit",
        calories: 82,
        vitamins: ["C", "E"],
        color: "orange",
    },
    {
        id: 193,
        name: "Acerola",
        category: "fruit",
        calories: 32,
        vitamins: ["C", "A"],
        color: "red",
    },
    {
        id: 194,
        name: "Sweetsop",
        category: "fruit",
        calories: 94,
        vitamins: ["C", "B1"],
        color: "green",
    },
    {
        id: 195,
        name: "Prickly Pear Fruit",
        category: "fruit",
        calories: 41,
        vitamins: ["C", "B6"],
        color: "pink",
    },
    {
        id: 196,
        name: "Naranjilla",
        category: "fruit",
        calories: 44,
        vitamins: ["C", "A"],
        color: "orange",
    },
    {
        id: 197,
        name: "Loquat (duplicate)",
        category: "fruit",
        calories: 47,
        vitamins: ["A", "C"],
        color: "yellow",
    },
    {
        id: 198,
        name: "Plantain (ripe)",
        category: "fruit",
        calories: 122,
        vitamins: ["B6", "C"],
        color: "yellow",
    },
    {
        id: 199,
        name: "Camu Camu",
        category: "fruit",
        calories: 17,
        vitamins: ["C"],
        color: "red",
    },
    {
        id: 200,
        name: "Guarana Fruit",
        category: "fruit",
        calories: 100,
        vitamins: ["C", "B2"],
        color: "red",
    },
];
